=== JGento98/CTaa20-21-JacopoGentili/es11.dtd
<!ELEMENT TEI (teiHeader, text,facsimile)*>
<!ELEMENT teiHeader (fileDesc, encodingDesc)>

<!ELEMENT fileDesc (titleStmt, publicationStmt, sourceDesc)>
<!ELEMENT encodingDesc (p)>

<!ELEMENT text (body)>
<!ELEMENT body (div)>
<!ELEMENT div (pb,opener, p)*>
<!ELEMENT p (#PCDATA|pc)*>
<!ELEMENT pb EMPTY>

<!ELEMENT titleStmt (title, author, respStmt)>
<!ELEMENT publicationStmt (p, publisher+, avalability)>
<!ELEMENT sourceDesc (bibl)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT respStmt (resp, name)>
<!ELEMENT publisher (#PCDATA|date)*>
<!ELEMENT avalability (p)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT bibl (title, author, pubPlace, date)>

<!ELEMENT opener (dateline, salute)>

<!ELEMENT dateline (#PCDATA|placeName|num|space|pc)*>
<!ELEMENT placeName (#PCDATA)>
<!ELEMENT num (#PCDATA)>

<!ELEMENT salute (#PCDATA|persName)*>
<!ELEMENT persName (#PCDATA|damage|choice)*>
<!ELEMENT space EMPTY> 
<!ELEMENT pc (#PCDATA)> 

<!ELEMENT resp (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT choice (#PCDATA|orig|reg)*>
<!ELEMENT orig (#PCDATA|damage)*>
<!ELEMENT damage (#PCDATA)*>
<!ELEMENT reg (#PCDATA)>
<!ELEMENT pubPlace (#PCDATA)>

<!ELEMENT facsimile (surface)>
<!ELEMENT surface (graphic|zone+)*>
<!ELEMENT graphic EMPTY>
<!ELEMENT zone EMPTY>

<!ATTLIST avalability status (free|unknown|restricted) #IMPLIED>
<!ATTLIST date when CDATA #IMPLIED>
<!ATTLIST div type CDATA #IMPLIED>
<!ATTLIST TEI xmlns CDATA "http://www.tei-c.org/ns/1.0">
<!ATTLIST placeName country CDATA #IMPLIED> 
<!ATTLIST placeName rend CDATA #IMPLIED> 
<!ATTLIST dateline lang CDATA #IMPLIED> 
<!ATTLIST num type (cardinal|ordinal|fraction|percentage) #IMPLIED>
<!ATTLIST damage agent CDATA #IMPLIED> 
<!ATTLIST space dim (vertical|horizontal) #IMPLIED> 
<!ATTLIST pc unit CDATA #IMPLIED> 

<!ATTLIST surface xml:id ID #IMPLIED> 
<!ATTLIST surface start CDATA #IMPLIED>
<!ATTLIST graphic url CDATA #IMPLIED> 
<!ATTLIST zone xml:id ID #IMPLIED> 
<!ATTLIST pb xml:id ID #IMPLIED> 

<!ATTLIST pb facs CDATA #IMPLIED> 
<!ATTLIST dateline facs CDATA #IMPLIED> 
<!ATTLIST salute facs CDATA #IMPLIED>
<!ATTLIST p facs CDATA #IMPLIED>  

<!ATTLIST surface ulx CDATA #IMPLIED>  
<!ATTLIST surface uly CDATA #IMPLIED> 
<!ATTLIST surface lrx CDATA #IMPLIED>  
<!ATTLIST surface lry CDATA #IMPLIED>

<!ATTLIST zone ulx CDATA #IMPLIED>  
<!ATTLIST zone uly CDATA #IMPLIED> 
<!ATTLIST zone lrx CDATA #IMPLIED>  
<!ATTLIST zone lry CDATA #IMPLIED>

=== JGento98/CTaa20-21-JacopoGentili/Esercizio11.xml
<?xml version="1.1" encoding="UTF-8"?>
<!--    WELL FORMED -->
<!DOCTYPE TEI SYSTEM "./es11.dtd">
<TEI xmlns = "http://www.tei-c.org/ns/1.0" >
 <!--TEI HEADER -->
 <teiHeader> 
        <fileDesc>
            <!-- sezione per la codifica del titolo dell'edizione digitale--> 
            <titleStmt> 
                <title>Lettera di Vincenzo Bellini a Carlo Pepoli</title>
                <author>Vincenzo Bellini</author>
                <respStmt>
                    <resp>Testo codificato dal testo originale con TEI P5 a cura di </resp>
                    <name>Jacopo Gentili </name>
                </respStmt>
            </titleStmt>

            <!-- Sezione per la codifica dei dati di diffusione e distribuzione dell'edizione-->
            <publicationStmt>
                  <p>Codifica di esercizio </p>
                  <publisher>Pastura <date when="1959">1959</date> </publisher>
                  <publisher>Neri <date when="2005">2005</date> </publisher>
                  <avalability status ="restricted"><p>No licenza</p></avalability>
            </publicationStmt>

            <!-- Descrizione fonte primaria -->
            <sourceDesc>
                <bibl>
                <title>Lettera di Bellini a Pepoli</title>
                <author>Vincenzo Bellini</author>
                <pubPlace> Puteaux </pubPlace>
                <date when="26/06/1834">26 giugno 1834</date>
                </bibl>
          </sourceDesc>

        </fileDesc>

        <encodingDesc>
            <p>Codifica in TEI P5 partendo dal manoscritto originale</p>    
        </encodingDesc>

 </teiHeader>
 <!-- FINE HEADER -->
    <text>
        <body>
            <div type = "lettera">
                <pb facs="#inizioLet" xml:id ="inizioPAG"/>
                <opener> 
                 <dateline lang ="FR" facs="#dataLine">
                     Juin <num>26</num><pc unit="colon">:</pc><placeName country="France">Puteau</placeName> <pc unit="Hyphen-minus">–</pc> N:°<num type="ordinal">19</num> bis rampe 
                        <space dim="vertical"></space>de<placeName country="France" rend="underline">Neuilly</placeName>
                 </dateline>
                 <salute facs="#Saluti">Mio caro 
                        <persName>
                            <choice>
                                <orig>Car<damage agent="time">lu</damage>ccio</orig>
                                <reg>Carlo</reg>
                            </choice>
                        </persName>
                 </salute>
                </opener>
                <p facs="#Inizio">avendo steso l<pc unit="Apostrophe">’</pc>intero duetto...</p>
            </div>
       </body>
    </text>
    <facsimile>
        <surface xml:id="inizioLet" start="#inizioPAG" ulx="0" uly="0" lrx='830' lry='301'>
                <graphic url='1.PNG'/>
                <zone xml:id="dataLine" ulx="4" uly="4" lrx="823" lry="129" />
                <zone xml:id="Saluti" ulx="4" uly="132" lrx="823" lry="190" />
                <zone xml:id="Inizio" ulx="3" uly="195" lrx="820" lry="296" />
            </surface>
    </facsimile>
</TEI>
